### PR TITLE
Basic orfs scripts

### PR DESCRIPTION
**Pull request by oharboe**
OpenROAD-flow-scripts: basic scripts to start investigating
    
1. Clone ORFS to https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts
2. Build https://github.com/The-OpenROAD-Project/OpenROAD-flow-scripts/blob/master/docs/user/BuildLocally.md
    
Run:

```    
$ ./orfs make YOSYS_FLAGS= DESIGN_CONFIG=config.mk synth
[deleted]
Creating register for signal `\TOP_MODULE.\resultSrcE' using process `\TOP_MODULE.$proc$Codes/RTL/TOP_MODULE.v:61$10'.
created $dff cERROR: Multiple edge sensitive events found for this signal!
Command exited with non-zero status 1
```

### CODE REVIEW

**Comment by jrrk2** [comment]
This kind of error usually means that you are updating a register from more than one always block. It should be simple to fix.

**Comment by oharboe** [comment]
@jrrk2 With #2 synthesis works w/Yosys.

**Comment by oharboe** [comment]
```
$ ./orfs make DESIGN_CONFIG=config.mk
[deleted]
=== TOP_MODULE ===

   Number of wires:             297617
   Number of wire bits:         297679
   Number of public wires:        2325
   Number of public wire bits:    2387
   Number of memories:               0
   Number of memory bits:            0
   Number of processes:              0
   Number of cells:             293953
     AND2x2_ASAP7_75t_R           8214
     AND2x4_ASAP7_75t_R             47
     AND3x1_ASAP7_75t_R          15672
     AND3x2_ASAP7_75t_R              3
     AND3x4_ASAP7_75t_R              1
     AND4x1_ASAP7_75t_R            431
     AND4x2_ASAP7_75t_R              2
     AND5x1_ASAP7_75t_R            105
     AND5x2_ASAP7_75t_R              2
     AO211x2_ASAP7_75t_R            50
     AO21x1_ASAP7_75t_R          41335
     AO21x2_ASAP7_75t_R              6
     AO221x1_ASAP7_75t_R           501
     AO222x2_ASAP7_75t_R           185
     AO22x1_ASAP7_75t_R            346
     AO22x2_ASAP7_75t_R              1
     AO31x2_ASAP7_75t_R             37
     AO32x1_ASAP7_75t_R            535
     AO33x2_ASAP7_75t_R             84
     AOI211x1_ASAP7_75t_R          235
     AOI21x1_ASAP7_75t_R          1975
     AOI221x1_ASAP7_75t_R          145
     AOI22x1_ASAP7_75t_R           193
     BUFx12f_ASAP7_75t_R             5
     BUFx2_ASAP7_75t_R           28525
     BUFx3_ASAP7_75t_R             873
     BUFx4f_ASAP7_75t_R             95
     BUFx6f_ASAP7_75t_R             67
     DFFASRHQNx1_ASAP7_75t_R       130
     DFFHQNx1_ASAP7_75t_R        37373
     DFFLQNx1_ASAP7_75t_R        10624
     FAx1_ASAP7_75t_R              528
     HAxp5_ASAP7_75t_R            3162
     INVx1_ASAP7_75t_R           24641
     INVx2_ASAP7_75t_R              12
     INVx3_ASAP7_75t_R               3
     NAND2x1_ASAP7_75t_R         28594
     NAND2x2_ASAP7_75t_R            48
     NAND3x1_ASAP7_75t_R           106
     NOR2x1_ASAP7_75t_R          22222
     NOR2x2_ASAP7_75t_R              8
     NOR3x1_ASAP7_75t_R            128
     NOR3x2_ASAP7_75t_R              3
     OA211x2_ASAP7_75t_R         24247
     OA21x2_ASAP7_75t_R          11431
     OA221x2_ASAP7_75t_R            15
     OA222x2_ASAP7_75t_R           101
     OA22x2_ASAP7_75t_R            223
     OA31x2_ASAP7_75t_R             82
     OA33x2_ASAP7_75t_R             60
     OAI21x1_ASAP7_75t_R          6644
     OAI22x1_ASAP7_75t_R           326
     OR2x2_ASAP7_75t_R            3082
     OR2x6_ASAP7_75t_R               1
     OR3x1_ASAP7_75t_R           18595
     OR3x2_ASAP7_75t_R               1
     OR4x1_ASAP7_75t_R             627
     OR4x2_ASAP7_75t_R               1
     OR5x1_ASAP7_75t_R             242
     TIEHIx1_ASAP7_75t_R             1
     TIELOx1_ASAP7_75t_R             1
     XNOR2x1_ASAP7_75t_R             6
     XNOR2x2_ASAP7_75t_R           599
     XOR2x2_ASAP7_75t_R            416

   Chip area for module '\TOP_MODULE': 35712.762300
```

**Comment by oharboe** [comment]
This is just a starting point, but here are the metrics. Improving this is left for followup PRs:

```
$ ./orfs make DESIGN_CONFIG=config.mk elapsed
[deleted]
Log                       Elapsed seconds
1_1_yosys                       1244
2_1_floorplan                     56
2_2_floorplan_io                   2
2_3_floorplan_tdms                 2
2_4_floorplan_macro                2
2_5_floorplan_tapcell             75
2_6_floorplan_pdn                192
3_1_place_gp_skip_io            2470
3_2_place_iop                     14
3_3_place_gp                    3298
3_4_place_resized                225
3_5_place_dp                     420
4_1_cts                        42699
5_1_grt                         8835
5_2_fillcell                     147
5_3_route                       5936
No elapsed time found in logs/asap7/riscv/base/6_1_merge.log
6_report                        2533
Total                          68150
```

2600um x 2600um. This is much larger than intended as I used the wrong units, `export CORE_UTILIZATION       = 0.50`, this is 0.5%, not 50% as intended.

image

image

```
>>> report_clock_min_period
clk period_min = 2662.15 fmax = 375.64
clk_2 period_min = 2615.13 fmax = 382.39
```

**Comment by oharboe** [comment]
To work on the settings, the next steps are:

1. Extract SRAMs as macros or create mock SRAMs.
2. Try `export CORE_UTILIZATION = 30`, 30%.
3. Write a proper .sdc file

**Comment by oharboe** [comment]
Doesnt appear to be any interest in this, can reopen if there is.

**Pull request closed without merging**
